### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [rakoo/rakoshare#4]
Dear Mr. Rakotojaona,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o Go?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by rakoo** [comment]
Hey @sergeevabc, sorry I can't seem to make cross-compiling work for Windows, it looks like the dependency on sqlite is problematic.... will have to migrate to some go-native thing i suppose (probably https://github.com/boltdb/bolt)

**Comment by sergeevabc** [comment]
@rakoo, did you get a chance to look into this more thoroughly?
